my_set1 = {1, 2, 3, 4}
my_set2 = {3,4,5,6}
my_set3 = my_set1 | my_set2 ##Union, me uno todos los elementos, y los duplicados no los agrego
print(f"union = {my_set3}")
my_set4 = my_set1 & my_set2 ##Interseccion, me tomo los elementos que esten en ambos sets
print(f"interseccion = {my_set4}")
my_set5 = my_set1 - my_set2 ##Diferencia, me tomo los elementos que esten en el set1 pero no en set2
print(f"diferencia = {my_set5}")
my_set6 = my_set1 ^ my_set2 ##Diferencia simetrica, me tomo los elementos que esten en el set1 o en set2, pero no en ambos
print(f"diferencia simetrica = {my_set6}")